"""config 积木 —— 配置加载（narnat.json / narnat.md / skills 解析、默认值、路径、系统提示词）。

契约来源：`openspec/changes/recast-v2/specs/config/spec.md`。
积木结构（design D1：跨积木只经显式接口；本积木只依赖标准库）：
- `config.defaults`：默认值中心（常量、prompt 模板、thinking 映射表、首次生成模板）；
- `config.models`：配置树数据类（零逻辑）；
- `config.parsers`：纯解析函数（narnat.json 原始 dict → 配置树节点）；
- `config.loader`：加载主流程（目录发现 → 生成默认文件 → 解析 → 组装配置树）；
- `config.skill_store`：技能加载（系统技能 / 项目技能发现 / 路径安全）。

聚合导出为积木对外接口；其余积木（llm / messages / tools / ui 等）仅从此处取配置。
"""
from __future__ import annotations

from . import defaults, loader, models, parsers, skill_store
from .defaults import (
    BASE_PROMPT_TEMPLATE,
    COMPRESS_PROMPT,
    CONFIG_SUBDIR,
    COST_LOG_FILENAME,
    DATA_SUBDIR,
    DEFAULT_API_KEY,
    DEFAULT_AUTO_SAVE,
    DEFAULT_AUTO_SAVE_TOKENS,
    DEFAULT_BALANCE_ENABLED,
    DEFAULT_BASE_URL,
    DEFAULT_COMPRESS_RATIO,
    DEFAULT_COMPRESS_RETAIN_TOKENS,
    DEFAULT_CONTEXT_WINDOW,
    DEFAULT_COST_LOG_MAX_BYTES,
    DEFAULT_COST_LOG_MAX_MB,
    DEFAULT_GIT_SKIP,
    DEFAULT_GOAL_MAX_ROUNDS,
    DEFAULT_IGNORE_DIRS,
    DEFAULT_LLM_RETRY_COUNT,
    DEFAULT_MAX_TIMEOUT_SECONDS,
    DEFAULT_MAX_TOOL_OUTPUT_KB,
    DEFAULT_MCP_STARTUP_TIMEOUT,
    DEFAULT_MCP_TOOL_TIMEOUT,
    DEFAULT_MIN_TOOLS,
    DEFAULT_MODEL,
    DEFAULT_PROTOCOL,
    DEFAULT_REQUIRE_PLAN,
    DEFAULT_RM_SKIP,
    DEFAULT_SHOW_BALANCE,
    DEFAULT_SHOW_COST,
    DEFAULT_SHOW_RATIO,
    DEFAULT_SKILL_SCAN_DEPTH,
    DEFAULT_THINKING_EFFORT,
    DEFAULT_THINKING_ENABLED,
    DEFAULT_THINKING_OPTIONS,
    DEFAULT_THINKING_PASSBACK,
    DEFAULT_UI_MAX_OUTPUT_TOKENS,
    DEFAULT_WARN_RATIO,
    LOGS_SUBDIR,
    NARNAT_DIR,
    NARNAT_JSON,
    NARNAT_MD,
    SESSIONS_SUBDIR,
    SKILLS_SUBDIR,
    SKILL_TREE_MAX_DEPTH,
    build_first_run_config,
    resolve_thinking_params,
    resolve_thinking_passback,
)
from .loader import (
    find_narnat_exe_dir,
    find_project_root,
    is_nuitka_onefile,
    load_config,
)
from .models import (
    AIConfig,
    BalanceConfig,
    Config,
    CostLogConfig,
    McpServerConfig,
    PathConfig,
    PlanConfig,
    PricingConfig,
    SafetyConfig,
    SessionConfig,
    SkillConfig,
    ToolConfig,
    UIConfig,
)
from .parsers import (
    build_ai_config,
    build_balance_config,
    build_cost_log_config,
    build_pricing_config,
    build_system_prompt,
    build_ui_config,
    coerce_value,
    parse_mcp_server,
    parse_model_config,
    parse_pricing,
    parse_project_skill_roots,
    parse_token_amount,
    strip_subagent_hidden,
)
from .skill_store import list_skill_tree, load_skill

__all__ = [
    # 子模块
    "defaults",
    "loader",
    "models",
    "parsers",
    "skill_store",
    # 加载入口与目录发现
    "find_narnat_exe_dir",
    "find_project_root",
    "is_nuitka_onefile",
    "load_config",
    # 配置树
    "AIConfig",
    "BalanceConfig",
    "Config",
    "CostLogConfig",
    "McpServerConfig",
    "PathConfig",
    "PlanConfig",
    "PricingConfig",
    "SafetyConfig",
    "SessionConfig",
    "SkillConfig",
    "ToolConfig",
    "UIConfig",
    # 解析函数
    "build_ai_config",
    "build_balance_config",
    "build_cost_log_config",
    "build_pricing_config",
    "build_system_prompt",
    "build_ui_config",
    "coerce_value",
    "parse_mcp_server",
    "parse_model_config",
    "parse_pricing",
    "parse_project_skill_roots",
    "parse_token_amount",
    "strip_subagent_hidden",
    # 技能
    "list_skill_tree",
    "load_skill",
    # 默认值 / 模板 / thinking 映射
    "BASE_PROMPT_TEMPLATE",
    "COMPRESS_PROMPT",
    "CONFIG_SUBDIR",
    "COST_LOG_FILENAME",
    "DATA_SUBDIR",
    "DEFAULT_API_KEY",
    "DEFAULT_AUTO_SAVE",
    "DEFAULT_AUTO_SAVE_TOKENS",
    "DEFAULT_BALANCE_ENABLED",
    "DEFAULT_BASE_URL",
    "DEFAULT_COMPRESS_RATIO",
    "DEFAULT_COMPRESS_RETAIN_TOKENS",
    "DEFAULT_CONTEXT_WINDOW",
    "DEFAULT_COST_LOG_MAX_BYTES",
    "DEFAULT_COST_LOG_MAX_MB",
    "DEFAULT_GIT_SKIP",
    "DEFAULT_GOAL_MAX_ROUNDS",
    "DEFAULT_IGNORE_DIRS",
    "DEFAULT_LLM_RETRY_COUNT",
    "DEFAULT_MAX_TIMEOUT_SECONDS",
    "DEFAULT_MAX_TOOL_OUTPUT_KB",
    "DEFAULT_MCP_STARTUP_TIMEOUT",
    "DEFAULT_MCP_TOOL_TIMEOUT",
    "DEFAULT_MIN_TOOLS",
    "DEFAULT_MODEL",
    "DEFAULT_PROTOCOL",
    "DEFAULT_REQUIRE_PLAN",
    "DEFAULT_RM_SKIP",
    "DEFAULT_SHOW_BALANCE",
    "DEFAULT_SHOW_COST",
    "DEFAULT_SHOW_RATIO",
    "DEFAULT_SKILL_SCAN_DEPTH",
    "DEFAULT_THINKING_EFFORT",
    "DEFAULT_THINKING_ENABLED",
    "DEFAULT_THINKING_OPTIONS",
    "DEFAULT_THINKING_PASSBACK",
    "DEFAULT_UI_MAX_OUTPUT_TOKENS",
    "DEFAULT_WARN_RATIO",
    "LOGS_SUBDIR",
    "NARNAT_DIR",
    "NARNAT_JSON",
    "NARNAT_MD",
    "SESSIONS_SUBDIR",
    "SKILLS_SUBDIR",
    "SKILL_TREE_MAX_DEPTH",
    "build_first_run_config",
    "resolve_thinking_params",
    "resolve_thinking_passback",
]
